// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qntqaogylsgpjcexuiyq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFudHFhb2d5bHNncGpjZXh1aXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NjQxMzUsImV4cCI6MjA3MjA0MDEzNX0.2ZFb0GjuFQNqE3LLM2xFPrh98oYQaTSxLZMgXuMUg08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});